import { FormEvent, useState } from "react";
import { Room } from "../api/taskApi";

interface Props { rooms: Room[]; selectedRoomId: number | null; onSelectPersonal: () => void; onSelectRoom: (room: Room) => void; onCreate: (name: string) => Promise<void>; onJoin: (code: string) => Promise<void>; onLeave: (room: Room) => Promise<void>; }

export default function RoomSidebar({ rooms, selectedRoomId, onSelectPersonal, onSelectRoom, onCreate, onJoin, onLeave }: Props) {
  const [roomName, setRoomName] = useState(""); const [code, setCode] = useState(""); const [open, setOpen] = useState<"create" | "join" | null>(null); const [error, setError] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); try { if (open === "create") { await onCreate(roomName); setRoomName(""); } else { await onJoin(code); setCode(""); } setOpen(null); } catch (reason) { setError(reason instanceof Error ? reason.message : "İşlem gerçekleştirilemedi."); } }
  return <aside className="w-full md:w-64 shrink-0 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm"><button onClick={onSelectPersonal} className={`w-full flex items-center gap-3 rounded-xl px-3 py-3 text-left text-sm ${selectedRoomId === null ? "bg-brand-50 text-brand-700 font-semibold" : "text-slate-600 hover:bg-slate-50"}`}><span className="grid size-7 place-items-center rounded-lg bg-brand-600 text-white">✓</span><span>Kişisel alanım</span></button><div className="mt-5 flex items-center justify-between px-2"><p className="text-[11px] font-semibold uppercase tracking-wider text-slate-400">Odalar</p><div className="flex gap-1"><button title="Oda oluştur" onClick={() => setOpen("create")} className="rounded p-1 text-brand-600 hover:bg-brand-50">+</button><button title="Koda katıl" onClick={() => setOpen("join")} className="rounded p-1 text-brand-600 hover:bg-brand-50">↗</button></div></div>{open && <form onSubmit={submit} className="mt-3 rounded-xl bg-slate-50 p-3 space-y-2"><input autoFocus value={open === "create" ? roomName : code} onChange={(e) => open === "create" ? setRoomName(e.target.value) : setCode(e.target.value)} placeholder={open === "create" ? "Oda adı" : "Giriş kodu"} className="field bg-white" required /><div className="flex gap-2"><button className="rounded-md bg-brand-600 px-3 py-1.5 text-xs font-medium text-white">{open === "create" ? "Oluştur" : "Katıl"}</button><button type="button" onClick={() => setOpen(null)} className="text-xs text-slate-500">Vazgeç</button></div>{error && <p className="text-xs text-red-600">{error}</p>}</form>}<div className="mt-2 space-y-1">{rooms.length === 0 && <p className="px-2 py-3 text-xs text-slate-400">Henüz bir odaya katılmadın.</p>}{rooms.map((room) => <div key={room.id} className={`group flex items-center rounded-xl ${selectedRoomId === room.id ? "bg-brand-50" : "hover:bg-slate-50"}`}><button onClick={() => onSelectRoom(room)} className={`min-w-0 flex-1 px-3 py-2.5 text-left text-sm ${selectedRoomId === room.id ? "font-semibold text-brand-700" : "text-slate-600"}`}><span className="block truncate">{room.name}</span><span className="block text-[10px] text-slate-400">{room._count.members} üye · {room._count.tasks} görev</span>{selectedRoomId === room.id && (
  <span className="block mt-1 text-[10px] text-slate-400">
    {room.members.map((member) => member.user.name).join(", ")}
  </span>
)}</button><button title="Odadan ayrıl" onClick={() => onLeave(room)} className="mr-2 hidden rounded px-1.5 py-1 text-xs text-red-400 hover:bg-red-50 group-hover:block">Ayrıl</button></div>)}</div></aside>;
}
